version: '3'

services:

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: application-db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - app-network
            
    app:
        build: .
        container_name: application-api
        ports:
            - "8080:8080"
        networks:
            - app-network
        entrypoint: ["java", "-jar", "produtos-api.jar"]
        depends_on:
            - db


networks:
    app-network:
        driver: bridge


