CREATE TABLE USUARIO (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;	

CREATE TABLE PERMISSAO (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	NOME VARCHAR(50) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USUARIO_PERMISSAO (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	USUARIO BIGINT(20) NOT NULL,
	PERMISSAO BIGINT(20) NOT NULL,
	FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (PERMISSAO) REFERENCES PERMISSAO(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO PERMISSAO(DESCRICAO) values ('ROLE_MERCADO');
INSERT INTO PERMISSAO(DESCRICAO) values ('ROLE_PRODUTO');
INSERT INTO PERMISSAO(DESCRICAO) values ('ROLE_MERCADORIA');

#senha: digital#9ers
INSERT INTO USUARIO (NOME, EMAIL, SENHA) values ('Admin', 'admin@projeto.com.br', '$2a$10$xp/mk.q2LxZ2djim4mOYYe2jaPzsBeMBocn3IRiGeTLoxgJXSMnz2');
INSERT INTO USUARIO (NOME, EMAIL, SENHA) values ('User', 'user@projeto.com.br', '$2a$10$xp/mk.q2LxZ2djim4mOYYe2jaPzsBeMBocn3IRiGeTLoxgJXSMnz2');

INSERT INTO USUARIO_PERMISSAO (USUARIO, PERMISSAO) values (1, 1);
INSERT INTO USUARIO_PERMISSAO (USUARIO, PERMISSAO) values (1, 2);
INSERT INTO USUARIO_PERMISSAO (USUARIO, PERMISSAO) values (1, 3);
INSERT INTO USUARIO_PERMISSAO (USUARIO, PERMISSAO) values (2, 1);

